<?php

/**
 * @file
 * Code for the govCMS CKAN Display module.
 */

/**
 * Implements hook_library().
 */
function govcms_ckan_display_library() {

  // Module path.
  $module_path = drupal_get_path('module', 'govcms_ckan_display');

  // Include custom charts libraries.
  $libraries['govcms_ckan_charts'] = array(
    'title' => 'govCMS CKAN Charts',
    'website' => 'http://www.govcms.gov.au',
    'version' => '1.0',
    'js' => array(
      array(
        'type' => 'file',
        'data' => $module_path . '/js/jquery.chart_export.js',
        'group' => JS_LIBRARY,
        'preprocess' => FALSE,
      ),
      array(
        'type' => 'file',
        'data' => $module_path . '/js/jquery.table_charts.js',
        'group' => JS_LIBRARY,
        'preprocess' => FALSE,
      ),
      array(
        'type' => 'file',
        'data' => $module_path . '/js/govcms_ckan_display.js',
        'group' => JS_LIBRARY,
        'preprocess' => FALSE,
      ),
    ),
  );

  // External Libraries (c3js & filesaver).
  // TODO: Ideally these should be stored locally but until the 'where to put
  // it' issue has been solved, we will just use external via a cdn.
  $libraries['c3js'] = array(
    'title' => 'c3js libraries',
    'website' => 'http://c3js.org',
    'version' => '0.4.10',
    'js' => array(
      array(
        'type' => 'external',
        'data' => 'https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.13/d3.js',
        'group' => JS_LIBRARY,
        'preprocess' => FALSE,
      ),
      array(
	'type' => 'external',
	'data' => 'https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.10/c3.min.js',
	'group' => JS_LIBRARY,
	'preprocess' => FALSE,
      ),
      array(
	'type' => 'external',
	'data' => 'https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2014-11-29/FileSaver.min.js',
	'group' => JS_LIBRARY,
	'preprocess' => FALSE,
      ),
      array(
	'type' => 'external',
	'data' => 'https://cdnjs.cloudflare.com/ajax/libs/javascript-canvas-to-blob/3.1.0/js/canvas-to-blob.min.js',
	'group' => JS_LIBRARY,
	'preprocess' => FALSE,
      ),
    ),
    'css' => array(
      array(
        'type' => 'external',
        'data' => 'https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.10/c3.css',
        'group' => CSS_DEFAULT,
        'preprocess' => FALSE,
      ),
    ),
  );
  $libraries['filesaver'] = array(
    'title' => 'c3js libraries',
    'website' => 'http://c3js.org',
    'version' => '0.4.10',
    'js' => array(
      array(
	'type' => 'external',
	'data' => 'https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2014-11-29/FileSaver.min.js',
	'group' => JS_LIBRARY,
	'preprocess' => FALSE,
      ),
      array(
	'type' => 'external',
	'data' => 'https://cdnjs.cloudflare.com/ajax/libs/javascript-canvas-to-blob/3.1.0/js/canvas-to-blob.min.js',
	'group' => JS_LIBRARY,
	'preprocess' => FALSE,
      ),
    ),
  );

  return $libraries;
}

/**
 * A helper to add charts to the provide selector.
 *
 * @param string $table_selector
 *   (optional) The jQuery selector for the tables you want to add charts to. If
 *   NULL then only the libraries will be added.
 */
function govcms_ckan_display_add_charts($table_selector = NULL) {
  // Include c3js library.
  drupal_add_library('govcms_ckan_display', 'c3js');
  // Include filesaver library.
  drupal_add_library('govcms_ckan_display', 'filesaver');
  // Include custom chart libs.
  drupal_add_library('govcms_ckan_display', 'govcms_ckan_charts');

  // Add the selector to drupal settings.
  if (!is_null($table_selector)) {
    drupal_add_js(array(
      'govcmsCkanDisplay' => array(
        'tableChartSelectors' => array($table_selector),
      ),
    ), 'setting');
  }
}
